POST http://localhost:3000/users
Content-Type: application/json 

{
    "name": "Sam",
    "email": "hsam@gmail.com",
    "password":"pass1234"
}

###

GET http://localhost:3000/users/hsam@gmail.com

{
    "email": "hsam@gmail.com",
    "password":"pass1234" 
}